# Default parameters used in the ViT architecture

DROPOUT_PROB = 0.1
BATCH_SIZE = 8
INPUT_CH = 3
INPUT_H = 224
INPUT_W = 224
NUM_CLASSES = 3

PATCH_SIZE = 16
EMBEDDING_DIM = 768
NUM_HEADS = 8
MLP_NEURONS = 2048
NUM_LAYERS = 6
NUM_PATCHES = (INPUT_H // PATCH_SIZE) * (INPUT_W // PATCH_SIZE)